2024-08-16 00:04:24.666 +07:00 [ERR] Unhandled UI Exception
System.Exception: No connection could be made because the target machine actively refused it. (localhost:5154)
   at ViewModels.ResponseService.ObjectResponse.Login(Object user) in D:\HocTap\CSharp\TrainWPF\ViewModels\ResponseService\ObjectResponse.cs:line 28
   at ViewModels.MainViewModels.MainViewModel.SetCurrentView() in D:\HocTap\CSharp\TrainWPF\ViewModels\MainViewModels\MainViewModel.cs:line 100
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-16 00:04:37.152 +07:00 [ERR] Unhandled UI Exception
System.Exception: No connection could be made because the target machine actively refused it. (localhost:5154)
   at ViewModels.ResponseService.ObjectResponse.Login(Object user) in D:\HocTap\CSharp\TrainWPF\ViewModels\ResponseService\ObjectResponse.cs:line 28
   at ViewModels.MainViewModels.MainViewModel.SetCurrentView() in D:\HocTap\CSharp\TrainWPF\ViewModels\MainViewModels\MainViewModel.cs:line 100
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-16 00:05:27.275 +07:00 [ERR] Unhandled UI Exception
System.Exception: No connection could be made because the target machine actively refused it. (localhost:5154)
   at ViewModels.ResponseService.ObjectResponse.Login(Object user) in D:\HocTap\CSharp\TrainWPF\ViewModels\ResponseService\ObjectResponse.cs:line 28
   at ViewModels.MainViewModels.MainViewModel.SetCurrentView() in D:\HocTap\CSharp\TrainWPF\ViewModels\MainViewModels\MainViewModel.cs:line 100
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-16 00:05:39.739 +07:00 [ERR] Unhandled UI Exception
System.Exception: No connection could be made because the target machine actively refused it. (localhost:5154)
   at ViewModels.ResponseService.ObjectResponse.Login(Object user) in D:\HocTap\CSharp\TrainWPF\ViewModels\ResponseService\ObjectResponse.cs:line 28
   at ViewModels.MainViewModels.MainViewModel.SetCurrentView() in D:\HocTap\CSharp\TrainWPF\ViewModels\MainViewModels\MainViewModel.cs:line 100
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-08-16 00:06:14.149 +07:00 [ERR] Unhandled UI Exception
System.Exception: No connection could be made because the target machine actively refused it. (localhost:5154)
   at ViewModels.ResponseService.ObjectResponse.Login(Object user) in D:\HocTap\CSharp\TrainWPF\ViewModels\ResponseService\ObjectResponse.cs:line 28
   at ViewModels.MainViewModels.MainViewModel.SetCurrentView() in D:\HocTap\CSharp\TrainWPF\ViewModels\MainViewModels\MainViewModel.cs:line 100
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
